### ISSUE TITLE
Problem with .ical content  file generation

### ISSUE THREAD

**Issue by kbies** [jjjj12212/EPESI-Ical#6]
Hello,

I have a problem with correct generation of .ical content;

/\* My steps */
I downloaded the source code files properly;

Installed it following by instruction steps;

I have done the step -->My Settings->Control Panel->Calendar Export Settings --> I checked all chceckboxes and typed my domain;

After this step the system correctly generate a ID;

This step was everything ok;

A go: _Menu->CRM->Calendar and clicked on "Export Calendar"_

/\* Problem effect _/
The effect of working this script is gerenated *.ical_ file <-- the file shows itself;

I opened (everytime when I open) this file by Notepad++, inside exists the comment:

" Invalid uid, Please use a different uid or generate a new one in Menu->My Settings->Control Panel->Calendar Export Settings "

/\* What I checked ? */
- Database connection is for sure working;
- Inside database exists table: **ical_hashlist** ;
- The query --> SELECT \* FROM ical_hashlist WHERE hash = /\* properly generated hash */ <-- works in PhpMyAdmin;
- the way to file is correctly declaraed in Ical_0.php

/\* My observations, conclusions */
- in my opinion it looks like a situation where the database doesn't display any calendar data (perhebs they exist) ;

Please tell me some hint or suggesion whats could be wrong and how to correct it;

**Comment by jjjj12212** [comment]
Hi kbies,

we haven't had a chance to make some modificatioins with the latest version of EPESI. We will take a look at this and try to update the project for you.

**Comment by jjjj12212** [comment]
Hi Kbies,

We have updated the package, please download the latest changes and overwrite the existing files.
If your still having an issue, please let us know.

**Comment by jjjj12212** [comment]
If your still having a problem Kbies, can you do the following:

turn on only meeting in the settings.
for domain, put in <company>.com

Check and see if that works.

**Comment by kbies** [comment]
**Thank** **you**. **It** **works**. The content of file is gereated;

It works also not even for .com domains;

It works for every option - meetings - tasks - phonecalls;

---

/\* Issue number 2 */

In the .ical content file exists an incorrect characters caused by incorrect character encoding (charset) (for my language).

Could you help me  to apply UTF-8 charset to .ical file ?

**Comment by jjjj12212** [comment]
Kbies,
lets try this:

modify modules/Premium/Ical/ical.php

change line 25 from:

header('Content-Type: text/calendar');

to

header('Content-Type: text/calendar; charset=UTF-8');

Let me know if that works..

regarding about the .com , I actually put in company.com as an example, not sure why it only showed .com but it was only an exmple though, glad that were progressing. :)

**Comment by jjjj12212** [comment]
If that didn't work, also try this:

 header( 'Content-Type: text/calendar; charset=utf-8' );

**Comment by kbies** [comment]
Yes, I tried this method, but its doesn't work (maybe it works, but doesn't solve my problem with characters )

In database I have correct characters (without any errors ) in **utf8_unicode_ci** encode format.

In export .ical file I don't have that kind of characters like: _ą_ , _ę_ , etc

So in my opinion it has to be something with charset encoding;

Do you have another idea ?

**Comment by kbies** [comment]
I also tried open each php file of ical by classic Notepad and save it in UTF-8 charset by hard and uploaded that files on server --> It also doesn't solved the problem

**Comment by jjjj12212** [comment]
Hi Kbies, ^ yeah I don't think that will give you the results you need, good try though :)

My Database also uses that encode format.

Can you post the actual data that is inside your database so I can copy, paste and test it?

Also what Calendar application are you exporting it to so I can test that as well?

Can you also, on the EPESI Forums, PM me your issue so I can send you my email address and you can attach the .ical so I can take a look at it.

I would put my email address here but I will get spammed.

Thanks.

**Comment by jjjj12212** [comment]
same username in EPESI FYI

**Comment by kbies** [comment]
Are you using this forum --> http://forum.epesibim.com/index.php ?

Sorry, I found you.

**Comment by jjjj12212** [comment]
Sent you a private message on the EPESI Forum

**Comment by jjjj12212** [comment]
This solution was solved. On line 53, you need to add:
$mysqli->set_charset('utf8');

which pumps out the correct characters from the database.
